apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: team-ecommerce
  labels:
    app.kubernetes.io/name: cartservice
    company.com/env: production
    company.com/team: ecommerce
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cartservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cartservice
        company.com/env: production
        company.com/team: ecommerce
    spec:
      containers:
      - name: server
        image: maestrops/cartservice:5-7df2473
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 15
          grpc:
            port: 7070
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          grpc:
            port: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: team-ecommerce
  labels:
    app.kubernetes.io/name: cartservice
    company.com/env: production
    company.com/team: ecommerce
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070

