apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: team-ecommerce
  labels:
    app.kubernetes.io/name: checkoutservice
    company.com/env: production
    company.com/team: ecommerce
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: checkoutservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkoutservice
        company.com/env: production
        company.com/team: ecommerce
    spec:
      containers:
        - name: server
          image: maestrops/checkoutservice:3-7df2473
          ports:
          - containerPort: 5050
          readinessProbe:
            grpc:
              port: 5050
          livenessProbe:
            grpc:
              port: 5050
          env:
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.team-ecommerce:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.team-platform:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice.team-finance:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice.team-marketing:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.team-platform:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice.team-ecommerce:7070"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: team-ecommerce
  labels:
    app.kubernetes.io/name: checkoutservice
    company.com/env: production
    company.com/team: ecommerce
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
