apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: team-platform
  labels:
    app.kubernetes.io/name: currencyservice
    company.com/env: production
    company.com/team: platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: currencyservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: currencyservice
        company.com/env: production
        company.com/team: platform
    spec:
      containers:
      - name: server
        image: maestrops/currencyservice:3-7df2473
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 7000
        livenessProbe:
          grpc:
            port: 7000
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: team-platform
  labels:
    app.kubernetes.io/name: currencyservice
    company.com/env: production
    company.com/team: platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: currencyservice
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000
