apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: team-finance
  labels:
    app.kubernetes.io/name: paymentservice
    company.com/env: production
    company.com/team: finance
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: paymentservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paymentservice
        company.com/env: production
        company.com/team: finance
    spec:
      containers:
      - name: server
        image: maestrops/paymentservice:2-7df2473
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 50051
        livenessProbe:
          grpc:
            port: 50051
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: team-finance
  labels:
    app.kubernetes.io/name: paymentservice
    company.com/env: production
    company.com/team: finance
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051