apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: team-platform
  labels:
    app.kubernetes.io/name: recommendationservice
    company.com/env: production
    company.com/team: platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: recommendationservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: recommendationservice
        company.com/env: production
        company.com/team: platform
    spec:
      containers:
      - name: server
        image: maestrops/recommendationservice:2-7df2473
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice.team-ecommerce:3550"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"  
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: team-platform
  labels:
    app.kubernetes.io/name: recommendationservice
    company.com/env: production
    company.com/team: platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: recommendationservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
